# Generated by Django 2.1.15 on 2022-04-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20220427_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
